# GNU Make solution makefile autogenerated by GENie
# Type "make help" for usage help

ifndef config
  config=debug32
endif
export config

PROJECTS := PlatDev_FileSystem

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

PlatDev_FileSystem: 
	@echo "==== Building PlatDev_FileSystem ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f PlatDev_FileSystem.make

clean:
	@${MAKE} --no-print-directory -C . -f PlatDev_FileSystem.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug32"
	@echo "   release32"
	@echo "   debug64"
	@echo "   release64"
	@echo "   debug"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   PlatDev_FileSystem"
	@echo ""
	@echo "For more information, see https://github.com/bkaradzic/genie"
